"""
Playbook overlay: renames and new plays from FND_Playbook_Reference.xlsx.
Generated by scripts/build_playbook_overlay.py — do not edit by hand.
"""
from __future__ import annotations

from typing import Dict, List

from models.play import Play, OffensivePlayCategory, DefensivePlayCategory

OFFENSIVE_RENAMES: Dict[str, dict] = {'double_wing_trap': {'metadata': {'ball_carrier': 'FB'}}, 'double_wing_toss_crack': {'name': 'Rocket Toss'}, 'dual_missile': {'name': 'Deep Out'}, 'flexbone_triple_option_dive': {'metadata': {'ball_carrier': 'RB or QB'}}, 'trey_wing_counter_sweep': {'name': 'QB Sweep', 'metadata': {'note': 'Ball carrier is QB'}}, 'wing_t_waggle_run': {'name': 'QB Counter', 'metadata': {'note': 'Ball carrier is QB'}}}

DEFENSIVE_RENAMES: Dict[str, dict] = {'34_dbl_war_0': {'name': 'All LB Pressure - 0'}, '34_saw_0': {'name': 'OLB Cover 0'}, '34_wag_1': {'name': 'Will A Gap - Cover 1'}, '34_favre_3': {'name': 'Favre 3 - Sim Pressure'}, '34_orton_4': {'name': 'Orton 4 - Sim Pressure'}, '34_weak_war_trey': {'name': 'Weak War Firezone'}, '43_mag_cover_1': {'name': 'Mike A Gap Cover 1'}, '43_spark_cover_0': {'name': 'LB/Safety Cover 0'}, 'nickel_saw_blue': {'name': 'Nickel Blitz Cover 1'}, 'nickel_war_blue': {'name': 'Will A Gap - Cover 1'}, 'nickel_favre': {'name': 'Nickel Sim Pressure 3'}, 'nickel_war_trey': {'name': 'Will A Gap - 3U3D'}}

OFFENSIVE_EXTRA_FORMATIONS: Dict[str, List[Play]] = {
    'Double Wing': [
        Play(
            id='double_wing_super_power',
            name='Super Power',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Double Wing',
            metadata={'ball_carrier': 'RB'},
        ),
    ],
    'Doubles': [
        Play(
            id='doubles_power_g',
            name='Power G',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Doubles',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='doubles_qb_power_g',
            name='QB Power G',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Doubles',
            metadata={'ball_carrier': 'QB'},
        ),
        Play(
            id='doubles_pin_n_pull',
            name='Pin n Pull',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Doubles',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='doubles_wave',
            name='Wave',
            side='offense',
            offensive_category=OffensivePlayCategory.LONG_PASS,
            formation='Doubles',
            metadata={},
        ),
        Play(
            id='doubles_snag',
            name='Snag',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Doubles',
            metadata={'note': 'Quick Game'},
        ),
    ],
    'Dual': [
        Play(
            id='dual_spacing',
            name='Spacing',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Dual',
            metadata={'concept': 'Quick Game'},
        ),
        Play(
            id='dual_q_counter',
            name='Q Counter',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Dual',
            metadata={'ball_carrier': 'QB'},
        ),
        Play(
            id='dual_snag',
            name='Snag',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Dual',
            metadata={},
        ),
        Play(
            id='dual_rb_counter',
            name='RB Counter',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Dual',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='dual_jet_sweep',
            name='Jet Sweep',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Dual',
            metadata={'ball_carrier': 'WR'},
        ),
    ],
    'Flexbone': [
        Play(
            id='flexbone_jet_sweep',
            name='Jet Sweep',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Flexbone',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='flexbone_fb_trap',
            name='FB Trap',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Flexbone',
            metadata={'ball_carrier': 'FB'},
        ),
    ],
    'Goalline': [
        Play(
            id='goalline_qb_sneak',
            name='QB Sneak',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Goalline',
            metadata={'ball_carrier': 'QB'},
        ),
        Play(
            id='goalline_fb_dive',
            name='FB Dive',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Goalline',
            metadata={'ball_carrier': 'FB'},
        ),
        Play(
            id='goalline_rb_iso',
            name='RB Iso',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Goalline',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='goalline_rb_sweep',
            name='RB Sweep',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Goalline',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='goalline_fake_fb_tb_sweep',
            name='Fake FB TB Sweep',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Goalline',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='goalline_pa_boot',
            name='PA Boot',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Goalline',
            metadata={},
        ),
        Play(
            id='goalline_power_pass',
            name='Power Pass',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Goalline',
            metadata={},
        ),
    ],
    'Trio': [
        Play(
            id='trio_snag',
            name='Snag',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Trio',
            metadata={},
        ),
        Play(
            id='trio_rb_dart',
            name='RB Dart',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Trio',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='trio_qb_dart',
            name='QB Dart',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Trio',
            metadata={'ball_carrier': 'QB'},
        ),
        Play(
            id='trio_qb_counter',
            name='QB Counter',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Trio',
            metadata={'ball_carrier': 'QB'},
        ),
        Play(
            id='trio_rb_counter',
            name='RB Counter',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Trio',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='trio_dagger',
            name='Dagger',
            side='offense',
            offensive_category=OffensivePlayCategory.MEDIUM_PASS,
            formation='Trio',
            metadata={},
        ),
    ],
    'Wide Slot': [
        Play(
            id='wide_slot_iso_insert',
            name='Iso Insert',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Wide Slot',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='wide_slot_dart',
            name='Dart',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Wide Slot',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='wide_slot_inside_zone',
            name='Inside Zone',
            side='offense',
            offensive_category=OffensivePlayCategory.INSIDE_RUN,
            formation='Wide Slot',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='wide_slot_pin_n_pull',
            name='Pin n Pull',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Wide Slot',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='wide_slot_outside_zone',
            name='Outside Zone',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Wide Slot',
            metadata={'ball_carrier': 'RB'},
        ),
        Play(
            id='wide_slot_speed_option',
            name='Speed Option',
            side='offense',
            offensive_category=OffensivePlayCategory.OUTSIDE_RUN,
            formation='Wide Slot',
            metadata={'ball_carrier': 'QB or RB'},
        ),
        Play(
            id='wide_slot_all_slants',
            name='All Slants',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_all_hitch',
            name='All Hitch',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_now_screen',
            name='Now Screen',
            side='offense',
            offensive_category=OffensivePlayCategory.SHORT_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_dagger',
            name='Dagger',
            side='offense',
            offensive_category=OffensivePlayCategory.MEDIUM_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_boot',
            name='Boot',
            side='offense',
            offensive_category=OffensivePlayCategory.MEDIUM_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_spin_dig',
            name='Spin - Dig',
            side='offense',
            offensive_category=OffensivePlayCategory.MEDIUM_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_deep_choice',
            name='Deep Choice',
            side='offense',
            offensive_category=OffensivePlayCategory.LONG_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_switch_choice',
            name='Switch Choice',
            side='offense',
            offensive_category=OffensivePlayCategory.LONG_PASS,
            formation='Wide Slot',
            metadata={},
        ),
        Play(
            id='wide_slot_slot_choice',
            name='Slot Choice',
            side='offense',
            offensive_category=OffensivePlayCategory.LONG_PASS,
            formation='Wide Slot',
            metadata={},
        ),
    ],
}

DEFENSIVE_EXTRA_FORMATIONS: Dict[str, List[Play]] = {
    '3-3 Stack': [
        Play(
            id='33stk_dog_lb_safety_cover_1',
            name='Dog - LB/Safety Cover 1',
            side='defense',
            defensive_category=DefensivePlayCategory.MAN_PRESSURE,
            formation='3-3 Stack',
            metadata={'note': 'LB Safety Pressure'},
        ),
        Play(
            id='33stk_all_lb_pressure_0',
            name='All LB Pressure - 0',
            side='defense',
            defensive_category=DefensivePlayCategory.MAN_PRESSURE,
            formation='3-3 Stack',
            metadata={'note': 'All out blitz, cover 0'},
        ),
    ],
    '3-3 Stack 3-High': [
        Play(
            id='33stk3h_cover_2',
            name='Cover 2',
            side='defense',
            defensive_category=DefensivePlayCategory.ZONES,
            formation='3-3 Stack 3-High',
            metadata={'note': 'Cover 2 Drop - Rush 3, good against passes'},
        ),
    ],
}

GOALLINE_FORMATION = "Goalline"
WIDE_SLOT_FORMATION = "Wide Slot"

def _apply_renames(plays: List[Play], renames: Dict[str, dict]) -> List[Play]:
    out: List[Play] = []
    for p in plays:
        patch = renames.get(p.id)
        if not patch:
            out.append(p)
            continue
        kwargs = dict(
            id=p.id,
            name=patch.get("name", p.name),
            side=p.side,
            offensive_category=p.offensive_category,
            defensive_category=p.defensive_category,
            formation=p.formation,
            metadata=patch.get("metadata", p.metadata),
        )
        out.append(Play(**kwargs))
    return out

def overlay_offensive_plays(formation: str, plays: List[Play]) -> List[Play]:
    merged = _apply_renames(list(plays), OFFENSIVE_RENAMES)
    extras = OFFENSIVE_EXTRA_FORMATIONS.get(formation, [])
    if not extras:
        return merged
    seen = {p.id for p in merged}
    for p in extras:
        if p.id not in seen:
            merged.append(p)
            seen.add(p.id)
    return merged

def overlay_defensive_plays(formation: str, plays: List[Play]) -> List[Play]:
    merged = _apply_renames(list(plays), DEFENSIVE_RENAMES)
    extras = DEFENSIVE_EXTRA_FORMATIONS.get(formation, [])
    if not extras:
        return merged
    seen = {p.id for p in merged}
    for p in extras:
        if p.id not in seen:
            merged.append(p)
            seen.add(p.id)
    return merged

def extra_offensive_formations() -> List[str]:
    return list(OFFENSIVE_EXTRA_FORMATIONS.keys())

